### ISSUE TITLE
Accepting pull requests?

### ISSUE THREAD

**Issue by duckcantcode** [ISibboI/wikitext-parser#1]
I just wrote a path selector for wikitext-parser. It allows you to take any element, and provide a "path" to match any set of elements you want. Think "xpath". Most elements take an `Option` that will select an index. It's not totally polished but if you're accepting PRs, I can clean it up.
```rs
section_selector(subsection.clone(), vec![Type::Paragraph(None), Type::Line(None), Type::TextPiece(None), Type::TextPieceDoubleBraced(None)].into());
```

**Comment by ISibboI** [comment]
Hi! Great that you find this code useful! I unfortunately don't have time for open source at the moment, so you are on your own. I recommend just forking this repo and publishing it yourself on crates.io under some new name.
